# Generated by Django 5.2.15 on 2026-07-05 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=True)),
                ('closed_message', models.TextField(default='Recruitment season is over and will begin next academic semester. Follow us on Instagram to hear when applications reopen.')),
            ],
            options={
                'verbose_name': 'Recruitment settings',
                'verbose_name_plural': 'Recruitment settings',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_study', models.CharField(choices=[('1', 'Year 1'), ('2', 'Year 2'), ('3', 'Year 3'), ('4', 'Year 4'), ('5', 'Year 5'), ('pg', 'Postgraduate')], max_length=2)),
                ('major', models.CharField(max_length=120)),
                ('current_choice', models.PositiveSmallIntegerField(default=1)),
                ('cv', models.FileField(upload_to='cvs/%Y/')),
                ('why_join', models.TextField(verbose_name='Why do you want to join HFR?')),
                ('experience', models.TextField(blank=True, verbose_name='Relevant experience or projects')),
                ('anything_else', models.TextField(blank=True, verbose_name='Anything else we should know?')),
                ('status', models.CharField(choices=[('submitted', 'Application submitted'), ('interview', 'Interview stage'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('applicant', 'Applicant'), ('onboarding', 'Onboarding HFR member'), ('member', 'Onboarded HFR member')], default='applicant', max_length=20)),
                ('preferred_name', models.CharField(blank=True, max_length=80)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('discord_handle', models.CharField(blank=True, max_length=80)),
                ('dietary_requirements', models.CharField(blank=True, max_length=160)),
                ('shirt_size', models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=4)),
                ('fun_fact', models.CharField(blank=True, max_length=200)),
                ('onboarded_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PromotionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_code', to='recruitment.application')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codes_issued', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=160)),
                ('is_recruiting', models.BooleanField(default=True)),
                ('leads', models.ManyToManyField(blank=True, related_name='led_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='alternative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alternative_applications', to='recruitment.team'),
        ),
        migrations.AddField(
            model_name='application',
            name='first_pick',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='first_pick_applications', to='recruitment.team'),
        ),
        migrations.AddField(
            model_name='application',
            name='wildcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wildcard_applications', to='recruitment.team'),
        ),
    ]
