# Generated by Django 5.2.15 on 2026-07-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_seed_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dietary_requirements',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='discord_handle',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fun_fact',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preferred_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='shirt_size',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_preset',
            field=models.CharField(blank=True, choices=[('h2-orange', 'H2 Orange'), ('h2-gold', 'H2 Gold'), ('h2-teal', 'H2 Teal'), ('h2-slate', 'H2 Slate')], max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact_method',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact_time',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('evening', 'Evening'), ('anytime', 'Anytime')], max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, help_text='You can also log in with this.', max_length=40, null=True, unique=True),
        ),
    ]
