# Generated by Django 5.2.15 on 2026-07-06 10:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_wireframe_questions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['division', 'name']},
        ),
        migrations.AddField(
            model_name='team',
            name='division',
            field=models.CharField(choices=[('land', 'Land'), ('sea', 'Sea'), ('air', 'Air'), ('operations', 'Operations')], default='land', max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('division', 'name'), name='unique_team_per_division'),
        ),
    ]
