# Generated by Django 5.2.15 on 2026-07-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0007_wireframe_subteams'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['division', 'sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='team',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
