# Generated by Django 5.2.15 on 2026-07-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0009_wireframe_team_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruitmentsettings",
            name="close_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Informational only. Shown on the register and signup pages; does not close signups on its own.",
                null=True,
            ),
        ),
    ]
