# Generated by Django 5.2.15 on 2026-08-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0010_recruitmentsettings_close_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "Application sent"),
                    ("under_review", "Application under review"),
                    ("interview", "Interview stage"),
                    ("decision_pending", "Decision pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="submitted",
                max_length=20,
            ),
        ),
    ]
