# Generated by Django 5.2.15 on 2026-09-14 12:39

import django.core.files.storage
import django.core.validators
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0012_new_division_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cv',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/Users/nooralghammari/HFR-website/private_media')), upload_to='cvs/%Y/', validators=[django.core.validators.FileExtensionValidator(['pdf'], 'Your CV must be a PDF.')]),
        ),
    ]
